name: Run Postman Collection

on:
  push:
    branches: [ main ]

jobs:
  postman-run:
    runs-on: ubuntu-latest
    env:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          npm install -g @postman/cli

      - name: Login to Postman
        run: |
          postman login --with-api-key $POSTMAN_API_KEY

      - name: Run Collection
        run: |
          postman collection run 40575281-935eaa39-6bbc-4894-ad32-757d2662d890 \
            -e 40575281-ab9cd626-c7bf-4e7b-be1e-34ecad14550
